development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: async
#  adapter: redis
#  url: redis://10.10.3.153:6381
#  url: <%#= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#  channel_prefix: ridesharing_app_production
